<?php

namespace App\Http\Livewire\Stock\Sp500;

use App\Models\Stock\SP500;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

class ByYear extends Component
{
    public $years = ['2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023'];
    public $selectedyear = '2023';
    public $total = 1;
    public $total_high;
    public $total_low;
    public $total_middle;

    public $less15;
    public $less30;
    public $less50;
    public $less100;

    public $rate = 0;
    public $rate_change = 0;
    public $rate_change_text = 0;
    public $rate_high = 0;
    public $rate_low = 0;


public function getData()
{


    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://www.plus500.com/en-AU/api/LiveData/FeedUpdate?instrumentID=18');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Authority: www.plus500.com';
    $headers[] = 'Accept: */*';
    $headers[] = 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8';
    $headers[] = 'Content-Type: text/plain';
    $headers[] = 'If-Modified-Since: '.Carbon::now()->format('D, d M Y H:i:s').' GMT';
    $headers[] = 'If-None-Match: \"a6e8e764-1a99-4c53-9523-e1f9757d284f\"';
    $headers[] = 'Referer: https://www.plus500.com/en-AU/Instruments/ES';
    $headers[] = 'Sec-Ch-Ua: \"Google Chrome\";v=\"111\", \"Not(A:Brand\";v=\"8\", \"Chromium\";v=\"111\"';
    $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
    $headers[] = 'Sec-Ch-Ua-Platform: \"macOS\"';
    $headers[] = 'Sec-Fetch-Dest: empty';
    $headers[] = 'Sec-Fetch-Mode: cors';
    $headers[] = 'Sec-Fetch-Site: same-origin';
    $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36';
    $headers[] = 'X-Requested-With: XMLHttpRequest';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    $array = json_decode($result,true);

//    "InstrumentID" => 18
//  "BuyPrice" => 4092.72
//  "SellPrice" => 4092.02
//  "HighPrice" => 4093.52
//  "LowPrice" => 4077.78
//  "ChangePercent" => 0.3
//  "ChangePercentText" => "0.30%"
//  "UsersBuyPercentage" => 50.0
//  "UsersSellPercentage" => 50.0
//  "IsSentimentValid" => true

//    $this->rate = $array['SellPrice'];
//    $this->rate_change = $array['ChangePercent'];
//    $this->rate_change_text = $array['ChangePercentText'];
//    $this->rate_high = $array['HighPrice'];
//    $this->rate_low = $array['LowPrice'];
}

    public function render()
    {
        $StartYear = Carbon::parse('2023-01-01');
        $StartPrice = SP500::where('date','>=',$StartYear)->OrderBy('date','asc')->first();
        $CurrentPrice = SP500::where('date','<=',Carbon::now()->format('Y-m-d'))->OrderBy('date','desc')->first();
        $days = $StartYear->diffInDays(Carbon::now());

        $contracts = 1;
        $OverNightBuy = 0.0262;
        $InvestmentValue = $contracts*$StartPrice->open;
        $fee = ($InvestmentValue/100*$OverNightBuy)*$days;

        $profit = ($CurrentPrice->close-$StartPrice->open)*$contracts-$fee;

        $Investment = $InvestmentValue/20;

        $rendite = 100/$Investment * $profit;

//        dd($StartPrice->open,$CurrentPrice->close,$InvestmentValue,$fee,$profit,$Investment,$rendite);

//        dd($fee);


        $this->getData();
        $this->total = DB::table('sp500s')->where('date','>=',$this->selectedyear.'-01-01')->count();
        $this->total_high = DB::table('sp500s')->whereColumn('close','>','open')->where('date','>=',$this->selectedyear.'-01-01')->count();
        $this->total_low = DB::table('sp500s')->whereColumn('open','>','close')->where('date','>=',$this->selectedyear.'-01-01')->count();
        $this->total_middle = DB::table('sp500s')->whereColumn('open','=','close')->where('date','>=',$this->selectedyear.'-01-01')->count();

        $stocks = SP500::where('date','>=',$this->selectedyear.'-01-01')->get();

        $this->less15 = 0;
        $this->less30 = 0;
        $this->less50 = 0;
        $this->less100 = 0;

        foreach ($stocks as $stock){
            if (($stock->high - $stock->low) <= 15){
                $this->less30 ++;
            }
            if (($stock->high - $stock->low) <= 30  && ($stock->high - $stock->low) > 15){
                $this->less15 ++;
            }
            if (($stock->high - $stock->low) <= 50  && ($stock->high - $stock->low) > 30){
                $this->less50 ++;
            }
            if (($stock->high - $stock->low) <= 100 && ($stock->high - $stock->low) > 50){
                $this->less100 ++;
            }
        }

        return view('livewire.stock.sp500.by-year');
    }
}
